name: Post welcome comment
on:
  pull_request:
    types:
      - "opened"
jobs:
  build:
    name: Post welcome comment
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      PR_URL: ${{ github.event.pull_request.html_url }}
    steps:
      - run: gh pr comment $PR_URL --body "1 Welcome to the repository!"
      - run: gh pr comment $PR_URL --body "2 Welcome to the repository!"
  build2:
    name: Post welcome comment
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      PR_URL: ${{ github.event.pull_request.html_url }}
    steps:
      - run: gh pr comment $PR_URL --body "3 Welcome to the repository!"
      - run: gh pr comment $PR_URL --body "4 Welcome to the repository!"
